name: wificlass-gpu
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - scipy
  - h5py
  - cudatoolkit=10.1
  - cudnn=7.6
  - tensorflow-gpu=2.1
  - tensorflow-estimator==2.1.0
  - keras-gpu
  - pillow
  - librosa
  - nltk
  - openpyxl
  - xlrd
  - tensorflow-datasets
  - hiplot
  - hyperopt
