name: wificlass
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - scipy
  - h5py
  - tensorflow=2
  - tensorflow-hub
  - keras
  - pillow
  - librosa
  - nltk
  - openpyxl
  - xlrd
  - tensorflow-datasets
  - hiplot
  - hyperopt
  - pytorch
  - stable-baselines3
  - gym-all

