name: wificlass-gpu
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.19.2
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - scipy
  - h5py
  - cudatoolkit
  - cudnn
  - tensorflow-gpu=2.1
  - tensorflow-estimator==2.1
  - keras-gpu
  - pillow
  - librosa
  - nltk
  - openpyxl
  - xlrd
  - tensorflow-datasets
  - hiplot
  - hyperopt
